relayer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'auth/logged-out.html', 'next_page': '/'}, name='logout'),
    url(r'^', include('streams.urls')),
]

streams/urls.py
from django.conf.urls import url

from . import views

app_name = 'streams'
urlpatterns = [
    # ex: /
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /settings/
    url(r'^settings/$', views.SettingsView.as_view(), name='settings'),
    # ex: /settings/generate_stream_key
    url(r'^settings/generate_stream_key', views.generate_stream_key_view,
        name='generate_steam_key'),
    # ex: /billy/
    url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name='detail'),
]

streams/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.dispatch import receiver
from django.db.models.signals import post_save

from .helpers import generate_stream_key

def generate_slug(stream_name):
    """
    Generates a slug based on stream_name
    """
    return slugify(stream_name)

class Stream(models.Model):
    """
    Defines the model of a stream or a "channel"
    that's owned by its creator
    """
    stream_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=20, unique=True)
    description = models.CharField(max_length=256, default='')
    stream_key = models.CharField(max_length=32, default=generate_stream_key)
    creation_date = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=1
    )

    def __str__(self):
        return self.stream_name

    def get_absolute_url(self):
        return reverse_lazy('settings')

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_stream_for_new_user(sender, created, instance, **kwargs):
    """
    Creates a new Stream object with a one-to-one relationship when a user is created
    """
    if created:
        stream = Stream(
            user=instance,
            stream_name=instance.username,
            slug=generate_slug(instance.username))
        stream.save()

streams/forms.py
from django.forms import ModelForm
from .models import Stream

class StreamForm(ModelForm):
    class Meta:
        model = Stream
        fields = ['stream_name', 'stream_key', 'description', 'is_private']
        labels = {
            'stream_name': ('Stream Title'),
            'stream_key': ('Stream Key'),
            'is_private': ('Private'),
        }

streams/views.py
from django.utils import timezone
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

from .helpers import generate_stream_key
from .models import Stream

class IndexView(generic.ListView):
    """
    Defines the index view that lists 20 streams
    """
    template_name = 'streams/index.html'
    context_object_name = 'latest_stream_list'

    def get_queryset(self):
        """
        Return the last 20 streams created, excluding private streams unless >staff
        """
        if self.request.user.is_staff:
            return Stream.objects.filter(
                creation_date__lte=timezone.now()
            ).order_by('-creation_date')[:20]
        else:
            return Stream.objects.filter(
                creation_date__lte=timezone.now(),
                is_private=False
            ).order_by('-creation_date')[:20]

class DetailView(generic.DetailView):
    """
    Defines the view for a single stream
    """
    model = Stream
    template_name = 'streams/detail.html'


class SettingsView(LoginRequiredMixin, generic.UpdateView):
    """
    Defines the view for a user's settings page
    """
    model = Stream
    fields = ['stream_name', 'description', 'stream_key', 'is_private']
    template_name = 'streams/settings.html'

    login_url = '/login/'
    success_url = '/settings' #placeholder while I wrangle with reverse/reverse_lazy

    def get_object(self, queryset=None):
        return Stream.objects.get(slug=self.request.user.stream.slug)

def generate_stream_key_view(request):
    return JsonResponse({'key': generate_stream_key()})

streams/templates/streams/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %} | Relayer</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="http://vjs.zencdn.net/5.16.0/video-js.css" rel="stylesheet">
    </head>
    {% include 'streams/nav.html' %}
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8= sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7 sha512-U6K1YLIFUWcvuw5ucmMtT9HH4t0uz3M366qrF5y4vnyH6dgDzndlcGvH/Lz5k8NFh80SN95aJ5rqGZEdaQZ7ZQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    {% block extra_scripts %} 
    {% endblock %}
</html>

streams/templates/streams/detail.html
{% extends 'streams/base.html' %}
{% block title %}{{ stream.stream_name }}{% endblock %}
{% load static %}

{% block content %}
    {% if stream.is_private and not user.is_authenticated %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            <strong>Private stream!</strong> You shall not pass.
        </div>
    </div>
    {% else %}
    <div class="container">
        <h1>{{ stream.stream_name }}</h1>

        <div class="embed-responsive">
            <video id="relayer-player" width=960 height=540 class="video-js vjs-default-skin vjs-16-9" controls>
                <source
                    src="{{ HLS_BASE_URL }}/{{ stream.stream_key }}/index.m3u8"
                    type="application/x-mpegURL">
            </video>
        </div>
        
    </div>

    <script src="http://vjs.zencdn.net/5.16.0/video.js"></script>
    <script src="{% static 'streams/lib/videojs-contrib-hls.min.js' %}"></script>
    <script>
    var player = videojs('relayer-player');
    player.play();
    </script>
    {% endif %}
{% endblock %}

streams/templates/streams/index.html
{% extends 'streams/base.html' %}
{% block title %}Streams Index{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Relayer</h1>
        <p>Relayer is a front-end for managing nginx-rtmp streams.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
</div>
<div class="container">
    <h2>Recent streams</h2>
{% if latest_stream_list %}
    <div class="card-columns">
    {% for stream in latest_stream_list %}
        <div class="card">
            <h3 class="card-header">{{ stream.stream_name }}</h3>
            <div class="card-block">
                <p class="card-text">{{ stream.description }}</p>
                <a class="btn btn-primary" href="{% url 'streams:detail' stream.slug %}">Watch {{ stream.stream_name }}</a>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p>No streams are available.</p>
{% endif %}
</div>
{% endblock %}

streams/templates/streams/nav.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Relayer</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Streams <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Recent Streams</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
                {% for stream in NAV_STREAM_LIST %}
                <a class="dropdown-item" href="{% url 'streams:detail' stream.slug %}">{{ stream.stream_name }}</a>
                {% endfor %}
            </div>
        </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="{% url 'streams:settings' %}">Settings</a>
                {% if user.is_staff %}<a class="dropdown-item" href="/admin">Admin</a> {% endif %}
                <a class="dropdown-item" href="/logout">Logout</a>
            </div>
        </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          </li>
        {% endif %}
    </ul>
    </div>
</nav>

streams/templates/streams/settings.html
{% extends 'streams/base.html' %}
{% load bootstrap %}
{% block title %}{{ stream.stream_name }} Settings{% endblock %}

{% block content %}
<div class="container">
<h1>Settings</h1>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    Stream Setup Information
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">RTMP URL: &nbsp; {{ RTMP_BASE_URL }}{{ user.stream.stream_key }}</li>
                    <li class="list-group-item">Public URL: &nbsp; <a href="{% url 'streams:detail' user.stream.slug %}"> {% url 'streams:detail' user.stream.slug %}</a></li>
                    <li class="list-group-item">
                        {% if user.stream.is_private %}
                            Only you and administrators can view your stream.
                        {% else %}
                            Anyone with the URL can view your stream.
                        {% endif %} 
                    </li>
                </ul>
                <div class="card-block">
                    <a href="https://obsproject.com/" class="card-link">Open Broadcaster Software</a>
                    <a href="https://www.xsplit.com/" class="card-link">XSplit</a>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    Edit Stream Settings
                </div>
                <div class="card-block">
                    <form class="form-settings" method="post">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <div class="form-group">
                        <button type="input" class="btn btn-warning" id="generate_new_stream_key">Generate New Stream Key</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
    $(function() {
        $('#generate_new_stream_key').click( function(e) {
            e.preventDefault();
            if(confirm("Are you sure you want to change your stream key?")) {
                $.getJSON("generate_stream_key/", function(data) {
                    console.log(data);
                    if(data.key) {
                        document.querySelector('#id_stream_key').value = data.key;
                    }
                })
            }

        })
    })
</script>
{% endblock %}